/* Demonstration placement only: no authoritative schedule is changed. */
const timetableDays=['Monday','Tuesday','Wednesday'],timetableTimes=['08:00','09:00'];
const timetableMeetings=[{id:'it-mon',course:'IT 101',room:'Room 201',day:0,time:0},{id:'it-wed',course:'IT 101',room:'Room 201',day:2,time:0},{id:'ge-tue',course:'GE 102',room:'Room 105',day:1,time:1}];
function meetingTime(value){const [hour,minute]=value.split(':').map(Number);return `${hour%12||12}:${String(minute).padStart(2,'0')} ${hour>=12?'PM':'AM'}`;}
function meetingEnd(value){const [hour,minute]=value.split(':').map(Number);return `${String(hour+1).padStart(2,'0')}:${String(minute).padStart(2,'0')}`;}
function meetingTiming(meeting){const start=timetableTimes[meeting.time];return `${meetingTime(start)}–${meetingTime(meetingEnd(start))} · 1 hour`;}
function weeklyTimetable(){return `<div class="table-scroll"><table class="schedule"><caption>Weekly timetable — fictional meetings. Drag a meeting to an empty slot, or select it to move with controls.</caption><thead><tr><th>Time</th>${timetableDays.map(day=>`<th>${day}</th>`).join('')}</tr></thead><tbody>${timetableTimes.map((time,t)=>`<tr><th>${meetingTime(time)}</th>${timetableDays.map((day,d)=>{const meeting=timetableMeetings.find(m=>m.day===d&&m.time===t);return `<td class="schedule-slot" data-day="${d}" data-time="${t}">${meeting?`<button class="meeting-drag" data-meeting="${meeting.id}" aria-label="Move ${meeting.course}, ${day}, ${time}"><span class="meeting-widget"><span class="meeting-heading"><strong>${meeting.course}</strong><span class="meeting-duration">${icon('clock')}1 hour</span></span><span class="meeting-clock"><span>${meetingTime(time)}</span>${icon('arrow-right')}<span>${meetingTime(meetingEnd(time))}</span></span><span class="meeting-meta"><span>${icon('calendar-days')}${day}</span><span>${icon('map-pin')}${meeting.room}</span></span></span></button>`:'<span class="empty-slot">Available</span>'}</td>`;}).join('')}</tr>`).join('')}</tbody></table></div><p id="timetable-status" class="demo-caption" role="status">Sample placements only. Drop on an available slot; select a meeting for keyboard move controls.</p>`;}
function placeDemoMeeting(id,day,time){const meeting=timetableMeetings.find(m=>m.id===id),occupied=timetableMeetings.find(m=>m.id!==id&&m.day===day&&m.time===time);if(occupied){document.getElementById('timetable-status').textContent=`Cannot move: ${timetableDays[day]} at ${meetingTime(timetableTimes[time])} already contains ${occupied.course}. Choose an available slot.`;return false;}meeting.day=day;meeting.time=time;const list=document.getElementById('meeting-list');if(list)list.innerHTML=timetableMeetings.map(m=>`<li>${m.course} · ${timetableDays[m.day]} · ${meetingTiming(m)} · ${m.room}</li>`).join('');const table=view.querySelector('.schedule').closest('.table-scroll'),status=document.getElementById('timetable-status');table.outerHTML=weeklyTimetable().split('<p id="timetable-status"')[0];status.textContent=`${meeting.course} moved to ${timetableDays[day]} at ${meetingTiming(meeting)}. Demonstration only.`;icons();return true;}
let timetableDrag,ignoreMeetingClick=false;
view.addEventListener('pointerdown',event=>{const button=event.target.closest('[data-meeting]');if(!button||event.button!==0)return;timetableDrag={button,id:button.dataset.meeting,x:event.clientX,y:event.clientY,moved:false};button.setPointerCapture(event.pointerId);});
view.addEventListener('pointermove',event=>{if(!timetableDrag)return;const state=timetableDrag;if(!state.moved&&Math.hypot(event.clientX-state.x,event.clientY-state.y)<6)return;state.moved=true;state.button.classList.add('is-dragging');view.querySelectorAll('.schedule-drop').forEach(e=>e.classList.remove('schedule-drop'));const slot=document.elementFromPoint(event.clientX,event.clientY)?.closest('.schedule-slot');if(slot)slot.classList.add('schedule-drop');});
function endTimetableDrag(event){if(!timetableDrag)return;const state=timetableDrag;timetableDrag=undefined;state.button.classList.remove('is-dragging');view.querySelectorAll('.schedule-drop').forEach(e=>e.classList.remove('schedule-drop'));if(state.moved){ignoreMeetingClick=true;setTimeout(()=>ignoreMeetingClick=false,0);const slot=document.elementFromPoint(event.clientX,event.clientY)?.closest('.schedule-slot');if(event.type==='pointerup'&&slot){placeDemoMeeting(state.id,Number(slot.dataset.day),Number(slot.dataset.time));view.querySelector(`[data-meeting="${state.id}"]`)?.focus();}}}
view.addEventListener('pointerup',endTimetableDrag);view.addEventListener('pointercancel',endTimetableDrag);
view.addEventListener('click',event=>{const button=event.target.closest('[data-meeting]');if(!button)return;event.preventDefault();event.stopImmediatePropagation();if(ignoreMeetingClick)return;const meeting=timetableMeetings.find(m=>m.id===button.dataset.meeting);openDemo('Move sample meeting',`<p>${meeting.course} · ${meeting.room}<br>${timetableDays[meeting.day]} · ${meetingTiming(meeting)}</p><p>Choose a placement in the fictional timetable. Each sample meeting lasts one hour.</p><form id="move-meeting" data-id="${meeting.id}"><label class="demo-field">Day<select class="text-input" name="day">${timetableDays.map((day,i)=>`<option value="${i}" ${i===meeting.day?'selected':''}>${day}</option>`).join('')}</select></label><label class="demo-field">Start time<select class="text-input" name="time">${timetableTimes.map((time,i)=>`<option value="${i}" ${i===meeting.time?'selected':''}>${meetingTime(time)}</option>`).join('')}</select></label><p id="move-error" class="error-text" role="alert"></p><div class="demo-row"><button type="button" class="secondary" data-close>Cancel</button><button class="primary">Move sample meeting</button></div></form>`);},true);
document.addEventListener('submit',event=>{if(event.target.id!=='move-meeting')return;event.preventDefault();const form=event.target,day=Number(form.elements.day.value),time=Number(form.elements.time.value);if(placeDemoMeeting(form.dataset.id,day,time)){dialog.close();view.querySelector(`[data-meeting="${form.dataset.id}"]`)?.focus();}else document.getElementById('move-error').textContent='That slot is occupied. Choose another day or time.';});
