<?php

namespace App\Filament\Resources\SchedulingDemands\Schemas;

use App\Models\SchedulingDemand;
use App\Models\TermOffering;
use Filament\Infolists\Components\TextEntry;
use Filament\Schemas\Components\Section;
use Filament\Schemas\Schema;

class SchedulingDemandInfolist
{
    public static function configure(Schema $schema): Schema
    {
        return $schema
            ->components([
                Section::make('Source Links')
                    ->schema([
                        TextEntry::make('demand_key')
                            ->copyable(),
                        TextEntry::make('termOffering.term.label')
                            ->label('Term'),
                        TextEntry::make('termOffering.curriculumEntry.courseSpecification.course.code')
                            ->label('Subject Code'),
                        TextEntry::make('termOffering.curriculumEntry.courseSpecification.title')
                            ->label('Subject Title'),
                        TextEntry::make('sectionDeliveryGroup.section.code')
                            ->label('Section'),
                        TextEntry::make('sectionDeliveryGroup.name')
                            ->label('Delivery Group'),
                        TextEntry::make('courseComponent.component_type')
                            ->label('Component')
                            ->badge(),
                        TextEntry::make('modality')
                            ->badge()
                            ->formatStateUsing(fn (?string $state): string => $state === null ? '-' : (TermOffering::modalityOptions()[$state] ?? str($state)->replace('_', ' ')->headline()->toString())),
                    ])
                    ->columns(3)
                    ->columnSpanFull(),
                Section::make('Readiness')
                    ->schema([
                        TextEntry::make('validation_state')
                            ->label('State')
                            ->badge()
                            ->formatStateUsing(fn (?string $state): string => $state === null ? '-' : (SchedulingDemand::validationStateOptions()[$state] ?? str($state)->headline()->toString()))
                            ->color(fn (?string $state): string => $state === null ? 'gray' : (SchedulingDemand::validationStateColors()[$state] ?? 'gray')),
                        TextEntry::make('readiness_messages')
                            ->label('Findings')
                            ->state(fn (SchedulingDemand $record): array => collect($record->readinessFindings())
                                ->map(fn (array $finding): string => "[{$finding['severity']}] {$finding['message']}")
                                ->whenEmpty(fn ($collection) => $collection->push('No readiness findings.'))
                                ->values()
                                ->all())
                            ->listWithLineBreaks()
                            ->columnSpanFull(),
                        TextEntry::make('readiness_checked_at')
                            ->dateTime(),
                        TextEntry::make('generator.name')
                            ->label('Generated By')
                            ->placeholder('-'),
                    ])
                    ->columns(2)
                    ->columnSpanFull(),
                Section::make('Demand Inputs')
                    ->schema([
                        TextEntry::make('required_duration_minutes')
                            ->label('Required Minutes')
                            ->numeric(),
                        TextEntry::make('meeting_count')
                            ->numeric(),
                        TextEntry::make('source_snapshot.expected_count')
                            ->label('Expected Count'),
                        TextEntry::make('source_snapshot.section_capacity')
                            ->label('Section Capacity'),
                        TextEntry::make('source_snapshot.room_type_requirement')
                            ->label('Room Type')
                            ->placeholder('-'),
                        TextEntry::make('source_snapshot.eligible_faculty_count')
                            ->label('Eligible Faculty'),
                        TextEntry::make('source_snapshot.suitable_room_count')
                            ->label('Suitable Rooms'),
                        TextEntry::make('source_snapshot.active_scheduling_window_count')
                            ->label('Scheduling Windows'),
                    ])
                    ->columns(4)
                    ->columnSpanFull(),
            ]);
    }
}
